#!/bin/sh
# Pre-commit hook that prevents a commit if the changed files
# don't pass linting requirements.
#
# When enabled, this hook can be bypassed by running `git commit --no-verify`


STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)
DIRNAME="$(git rev-parse --show-toplevel)"
ESLINT="$DIRNAME/node_modules/.bin/eslint"

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

printf "\nValidating...\n"

# Check for eslint
if [[ ! -x "$ESLINT" ]]; then
  printf "\t\033[41mPlease install ESlint\033[0m (npm i --save-dev eslint)"
  exit 1
fi
"$ESLINT" $(printf "$STAGED_FILES")
if [[ "$?" != 0 ]]; then
    PASS=false
fi



if ! $PASS; then
  printf "\033[31mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
else
  printf "\n\033[32mCOMMIT VALID.\033[0m Proceeding...\n\n"
fi

exit $?
